[package]
name = "collapsepatcher"
version = "0.1.0"
edition = "2021"
description = "A tool for patching JARS."

[dependencies]
zip = "7.4.0"
ristretto_classfile = "0.29.0"
rand = "0.10.0"
rayon = "1.11.0"
base64 = "0.22.1"
clap = { version = "4.5.58", features = ["derive"] }
